export const INCREMENT_ENTHUSIASM = 'INCREMENT_ENTHUSIASM';
export type INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const INCREMENT_ASYNC_ENTHUSIASM = 'INCREMENT_ASYNC_ENTHUSIASM';
export type INCREMENT_ASYNC_ENTHUSIASM = typeof INCREMENT_ASYNC_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = 'DECREMENT_ENTHUSIASM';
export type DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;